/******************************************************
 * This is the main file for the mips ArchC model     *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/


const char *project_name="mips";
const char *project_file="mips.ac";
const char *archc_version="2.2";
const char *archc_options="-abi ";

#include  <iostream>
#include  <systemc.h>
#include  "ac_stats_base.H"
#include  "mips.H"

#include  "ac_tlm_mem.h"
#include  "ac_tlm_router.h"
#include  "ac_tlm_peripheral.h"
#include  "ac_tlm_trigonometric.h"
#include  "ac_tlm_float.h"

using user::ac_tlm_mem;
using user::ac_tlm_router;
using user::ac_tlm_peripheral;
using user::ac_tlm_trigonometric;
using user::ac_tlm_float;

int sc_main(int ac, char *av[])
{

  //!  ISA simulator
  mips mips_proc1("mips");
  mips mips_proc2("mips2");
  mips mips_proc3("mips3");
  mips mips_proc4("mips4");


  ac_tlm_mem mem("mem", 100*1024*1024);
  ac_tlm_router router("router");
  ac_tlm_peripheral peripheral("peripheral");
  ac_tlm_trigonometric trig_acc("trig_acc");
  ac_tlm_float float_acc("float_acc");


  int ac1 = ac;
  int ac2 = ac;
  int ac3 = ac;
  char *av1[2];
  (av1[0]) = strdup(av[0]);
  (av1[1]) = strdup(av[1]);
  char *av2[2];
  (av2[0]) = strdup(av[0]);
  (av2[1]) = strdup(av[1]);
  char *av3[2];
  (av3[0]) = strdup(av[0]);
  (av3[1]) = strdup(av[1]);


  router.MEM_port(mem.target_export);
  router.PERIPHERAL_port(peripheral.target_export);
  router.TRIG_ACC_port(trig_acc.target_export);
  router.FLOAT_ACC_port(float_acc.target_export);

  mips_proc1.DM_port(router.target_export);
  mips_proc2.DM_port(router.target_export);
  mips_proc3.DM_port(router.target_export);
  mips_proc4.DM_port(router.target_export);


#ifdef AC_DEBUG
  ac_trace("mips_proc1.trace");
  ac_trace("mips_proc2.trace");
  ac_trace("mips_proc3.trace");
  ac_trace("mips_proc4.trace");
#endif

  mips_proc1.init(ac, av);
  cerr << endl;
  mips_proc2.init(ac1, av1);
  cerr << endl;
  mips_proc3.init(ac2, av2);
  cerr << endl;
  mips_proc4.init(ac3, av3);
  cerr << endl;

  mips_proc1.set_instr_batch_size(1);
  mips_proc2.set_instr_batch_size(1);
  mips_proc3.set_instr_batch_size(1);
  mips_proc4.set_instr_batch_size(1);

  sc_start();

  mips_proc1.PrintStat();
  cerr << endl;
  mips_proc2.PrintStat();
  cerr << endl;
  mips_proc3.PrintStat();
  cerr << endl;
  mips_proc4.PrintStat();
  cerr << endl;

#ifdef AC_STATS
  ac_stats_base::print_all_stats(std::cerr);
#endif

#ifdef AC_DEBUG
  ac_close_trace();
#endif

  return mips_proc1.ac_exit_status + mips_proc2.ac_exit_status +
         mips_proc3.ac_exit_status + mips_proc4.ac_exit_status;

}
